baseURL = "http://math.iisc.ac.in/~gadgil/topology-2022/"
languageCode = "en-us"
title = "MA 231: Topology"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 231"
    course = "Topology"
    term = "August 2022"
[markup.goldmark.renderer]
unsafe= true